######################################################################
# Automatically generated by qmake (2.01a) ?? 28. ??? 11:05:48 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
